/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1ResidentsGet$Params {
  search?: string;
  skip?: number;
  take?: number;
  apartmentId?: string;
}

export function apiV1ResidentsGet(http: HttpClient, rootUrl: string, params?: ApiV1ResidentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1ResidentsGet.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('skip', params.skip, {});
    rb.query('take', params.take, {});
    rb.query('apartmentId', params.apartmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1ResidentsGet.PATH = '/api/v1/residents';
