/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ChangePasswordRequest } from './models/change-password-request';
export type { CreateApartmentRequest } from './models/create-apartment-request';
export type { CreateAttendantProfileRequest } from './models/create-attendant-profile-request';
export type { CreateAuditLogRequest } from './models/create-audit-log-request';
export type { CreateConfigurationRequest } from './models/create-configuration-request';
export type { CreateGatehouseRequest } from './models/create-gatehouse-request';
export type { CreatePorteiroRequest } from './models/create-porteiro-request';
export type { CreateResidentRequest } from './models/create-resident-request';
export type { CreateServiceProviderRequest } from './models/create-service-provider-request';
export type { CreateShiftRequest } from './models/create-shift-request';
export type { CreateTenantAdminRequest } from './models/create-tenant-admin-request';
export type { CreateTenantRequest } from './models/create-tenant-request';
export type { CreateUserRequest } from './models/create-user-request';
export type { CreateVehicleRequest } from './models/create-vehicle-request';
export type { CreateVisitRequest } from './models/create-visit-request';
export type { DemoSeederService } from './models/demo-seeder-service';
export type { LoginRequest } from './models/login-request';
export type { RefreshRequest } from './models/refresh-request';
export type { ResumeTenantRequest } from './models/resume-tenant-request';
export type { SuspendTenantRequest } from './models/suspend-tenant-request';
export type { TenantSwitchRequest } from './models/tenant-switch-request';
export type { UpdateApartmentRequest } from './models/update-apartment-request';
export type { UpdateAttendantProfileRequest } from './models/update-attendant-profile-request';
export type { UpdateConfigurationRequest } from './models/update-configuration-request';
export type { UpdateResidentRequest } from './models/update-resident-request';
export type { UpdateServiceProviderRequest } from './models/update-service-provider-request';
export type { UpdateTenantAdminRequest } from './models/update-tenant-admin-request';
export type { UpdateVehicleRequest } from './models/update-vehicle-request';
export type { VehicleType } from './models/vehicle-type';
