<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ControlEasyReborn.Modules.AccessControl.Application</RootNamespace>
    <AssemblyName>ControlEasyReborn.Modules.AccessControl.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ControlEasyReborn.Modules.AccessControl.Domain\ControlEasyReborn.Modules.AccessControl.Domain.csproj" />
    <ProjectReference Include="..\..\Residents\ControlEasyReborn.Modules.Residents.Application\ControlEasyReborn.Modules.Residents.Application.csproj" />
    <ProjectReference Include="..\..\Vehicles\ControlEasyReborn.Modules.Vehicles.Application\ControlEasyReborn.Modules.Vehicles.Application.csproj" />
    <ProjectReference Include="..\..\Apartments\ControlEasyReborn.Modules.Apartments.Application\ControlEasyReborn.Modules.Apartments.Application.csproj" />
    <ProjectReference Include="..\..\Photos\ControlEasyReborn.Modules.Photos.Application\ControlEasyReborn.Modules.Photos.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Mapster" />
  </ItemGroup>
</Project>
