/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1ReportsHistoryGet$Params {
  page?: number;
  pageSize?: number;
  from?: string;
  to?: string;
  status?: string;
  carrierCode?: string;
  q?: string;
  apartmentId?: string;
}

export function apiV1ReportsHistoryGet(http: HttpClient, rootUrl: string, params?: ApiV1ReportsHistoryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1ReportsHistoryGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('status', params.status, {});
    rb.query('carrierCode', params.carrierCode, {});
    rb.query('q', params.q, {});
    rb.query('apartmentId', params.apartmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1ReportsHistoryGet.PATH = '/api/v1/reports/history';
