/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePorteiroRequest } from '../../models/create-porteiro-request';

export interface ApiV1TenantsIdPorteirosPost$Params {
  id: string;
  body: CreatePorteiroRequest;
}

export function apiV1TenantsIdPorteirosPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiV1TenantsIdPorteirosPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1TenantsIdPorteirosPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

apiV1TenantsIdPorteirosPost.PATH = '/api/v1/tenants/{id}/porteiros';
