/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateTenantAdminRequest } from '../../models/update-tenant-admin-request';

export interface ApiV1TenantsIdAdminsUserIdPut$Params {
  id: string;
  userId: string;
      body: UpdateTenantAdminRequest
}

export function apiV1TenantsIdAdminsUserIdPut(http: HttpClient, rootUrl: string, params: ApiV1TenantsIdAdminsUserIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1TenantsIdAdminsUserIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1TenantsIdAdminsUserIdPut.PATH = '/api/v1/tenants/{id}/admins/{userId}';
