/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateAttendantProfileRequest } from '../../models/update-attendant-profile-request';

export interface ApiV1SecurityAttendantProfilesIdPut$Params {
  id: string;
      body: UpdateAttendantProfileRequest
}

export function apiV1SecurityAttendantProfilesIdPut(http: HttpClient, rootUrl: string, params: ApiV1SecurityAttendantProfilesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1SecurityAttendantProfilesIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1SecurityAttendantProfilesIdPut.PATH = '/api/v1/security/attendant-profiles/{id}';
