/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface ApiV1SecurityAttendantProfilesIdDeactivatePost$Params {
  id: string;
}

export function apiV1SecurityAttendantProfilesIdDeactivatePost(
  http: HttpClient,
  rootUrl: string,
  params: ApiV1SecurityAttendantProfilesIdDeactivatePost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1SecurityAttendantProfilesIdDeactivatePost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

apiV1SecurityAttendantProfilesIdDeactivatePost.PATH = '/api/v1/security/attendant-profiles/{id}/deactivate';
