/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1AccessEventsGet$Params {
  fromUtc?: string;
  toUtc?: string;
  direction?: string;
  subjectType?: string;
  subjectId?: string;
  credentialStatus?: string;
  gatehouseId?: string;
  attendantProfileId?: string;
  skip?: number;
  take?: number;
}

export function apiV1AccessEventsGet(http: HttpClient, rootUrl: string, params?: ApiV1AccessEventsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccessEventsGet.PATH, 'get');
  if (params) {
    rb.query('fromUtc', params.fromUtc, {});
    rb.query('toUtc', params.toUtc, {});
    rb.query('direction', params.direction, {});
    rb.query('subjectType', params.subjectType, {});
    rb.query('subjectId', params.subjectId, {});
    rb.query('credentialStatus', params.credentialStatus, {});
    rb.query('gatehouseId', params.gatehouseId, {});
    rb.query('attendantProfileId', params.attendantProfileId, {});
    rb.query('skip', params.skip, {});
    rb.query('take', params.take, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1AccessEventsGet.PATH = '/api/v1/access-events';
