<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ControlEasyReborn.Modules.Residents.Application</RootNamespace>
    <AssemblyName>ControlEasyReborn.Modules.Residents.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ControlEasyReborn.Modules.Residents.Domain\ControlEasyReborn.Modules.Residents.Domain.csproj" />
    <ProjectReference Include="..\..\Apartments\ControlEasyReborn.Modules.Apartments.Application\ControlEasyReborn.Modules.Apartments.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>