/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface ApiV1EntryLogExportGet$Params {
  entryState?: string;
  subjectType?: string;
  fromUtc?: string;
  toUtc?: string;
}

export function apiV1EntryLogExportGet(
  http: HttpClient,
  rootUrl: string,
  params?: ApiV1EntryLogExportGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1EntryLogExportGet.PATH, 'get');
  if (params) {
    rb.query('entryState', params.entryState, {});
    rb.query('subjectType', params.subjectType, {});
    rb.query('fromUtc', params.fromUtc, {});
    rb.query('toUtc', params.toUtc, {});
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

apiV1EntryLogExportGet.PATH = '/api/v1/entry-log/export';
