<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>ControlEasyReborn.Api</RootNamespace>
    <AssemblyName>ControlEasyReborn.Api</AssemblyName>
    <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    <MakeApplicationEntrypointPublic>true</MakeApplicationEntrypointPublic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\ControlEasyReborn.Infrastructure\ControlEasyReborn.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ControlEasyReborn.SharedKernel\ControlEasyReborn.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Modules\Tenants\ControlEasyReborn.Modules.Tenants.Api\ControlEasyReborn.Modules.Tenants.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Tenants\ControlEasyReborn.Modules.Tenants.Application\ControlEasyReborn.Modules.Tenants.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Tenants\ControlEasyReborn.Modules.Tenants.Infrastructure\ControlEasyReborn.Modules.Tenants.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Residents\ControlEasyReborn.Modules.Residents.Api\ControlEasyReborn.Modules.Residents.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Apartments\ControlEasyReborn.Modules.Apartments.Api\ControlEasyReborn.Modules.Apartments.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Apartments\ControlEasyReborn.Modules.Apartments.Application\ControlEasyReborn.Modules.Apartments.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Apartments\ControlEasyReborn.Modules.Apartments.Infrastructure\ControlEasyReborn.Modules.Apartments.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Residents\ControlEasyReborn.Modules.Residents.Application\ControlEasyReborn.Modules.Residents.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Residents\ControlEasyReborn.Modules.Residents.Infrastructure\ControlEasyReborn.Modules.Residents.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Security\ControlEasyReborn.Modules.Security.Api\ControlEasyReborn.Modules.Security.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Security\ControlEasyReborn.Modules.Security.Application\ControlEasyReborn.Modules.Security.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Security\ControlEasyReborn.Modules.Security.Infrastructure\ControlEasyReborn.Modules.Security.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Administration\ControlEasyReborn.Modules.Administration.Api\ControlEasyReborn.Modules.Administration.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Administration\ControlEasyReborn.Modules.Administration.Application\ControlEasyReborn.Modules.Administration.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Administration\ControlEasyReborn.Modules.Administration.Infrastructure\ControlEasyReborn.Modules.Administration.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\ServiceProviders\ControlEasyReborn.Modules.ServiceProviders.Api\ControlEasyReborn.Modules.ServiceProviders.Api.csproj" />
    <ProjectReference Include="..\..\Modules\ServiceProviders\ControlEasyReborn.Modules.ServiceProviders.Application\ControlEasyReborn.Modules.ServiceProviders.Application.csproj" />
    <ProjectReference Include="..\..\Modules\ServiceProviders\ControlEasyReborn.Modules.ServiceProviders.Infrastructure\ControlEasyReborn.Modules.ServiceProviders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Vehicles\ControlEasyReborn.Modules.Vehicles.Api\ControlEasyReborn.Modules.Vehicles.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Vehicles\ControlEasyReborn.Modules.Vehicles.Application\ControlEasyReborn.Modules.Vehicles.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Visits\ControlEasyReborn.Modules.Visits.Api\ControlEasyReborn.Modules.Visits.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Visits\ControlEasyReborn.Modules.Visits.Application\ControlEasyReborn.Modules.Visits.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Visits\ControlEasyReborn.Modules.Visits.Infrastructure\ControlEasyReborn.Modules.Visits.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Reports\ControlEasyReborn.Modules.Reports.Api\ControlEasyReborn.Modules.Reports.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Reports\ControlEasyReborn.Modules.Reports.Application\ControlEasyReborn.Modules.Reports.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Reports\ControlEasyReborn.Modules.Reports.Infrastructure\ControlEasyReborn.Modules.Reports.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="AspNetCore.HealthChecks.MySql" />
    <PackageReference Include="Microsoft.FeatureManagement" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>
</Project>