/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1AccessCredentialsGet$Params {
  subjectType?: string;
  subjectId?: string;
  status?: string;
  skip?: number;
  take?: number;
}

export function apiV1AccessCredentialsGet(http: HttpClient, rootUrl: string, params?: ApiV1AccessCredentialsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AccessCredentialsGet.PATH, 'get');
  if (params) {
    rb.query('subjectType', params.subjectType, {});
    rb.query('subjectId', params.subjectId, {});
    rb.query('status', params.status, {});
    rb.query('skip', params.skip, {});
    rb.query('take', params.take, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1AccessCredentialsGet.PATH = '/api/v1/access-credentials';
