/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateAuditLogRequest } from '../../models/create-audit-log-request';

export interface ApiV1AdministrationAuditLogsPost$Params {
  body: CreateAuditLogRequest;
}

export function apiV1AdministrationAuditLogsPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiV1AdministrationAuditLogsPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdministrationAuditLogsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

apiV1AdministrationAuditLogsPost.PATH = '/api/v1/administration/audit-logs';
