/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateConfigurationRequest } from '../../models/update-configuration-request';

export interface ApiV1AdministrationConfigurationsIdPut$Params {
  id: string;
  body: UpdateConfigurationRequest;
}

export function apiV1AdministrationConfigurationsIdPut(
  http: HttpClient,
  rootUrl: string,
  params: ApiV1AdministrationConfigurationsIdPut$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdministrationConfigurationsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

apiV1AdministrationConfigurationsIdPut.PATH = '/api/v1/administration/configurations/{id}';
