/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1AdministrationAuditLogsEntityEntityIdGet$Params {
  entityId: string;
  skip?: number;
  take?: number;
}

export function apiV1AdministrationAuditLogsEntityEntityIdGet(http: HttpClient, rootUrl: string, params: ApiV1AdministrationAuditLogsEntityEntityIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdministrationAuditLogsEntityEntityIdGet.PATH, 'get');
  if (params) {
    rb.path('entityId', params.entityId, {});
    rb.query('skip', params.skip, {});
    rb.query('take', params.take, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1AdministrationAuditLogsEntityEntityIdGet.PATH = '/api/v1/administration/audit-logs/entity/{entityId}';
