/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface ApiV1AdministrationAuditLogsGet$Params {
  category?: string;
  severity?: string;
  entityType?: string;
  action?: string;
  fromUtc?: string;
  toUtc?: string;
  searchTerm?: string;
  skip?: number;
  take?: number;
}

export function apiV1AdministrationAuditLogsGet(
  http: HttpClient,
  rootUrl: string,
  params?: ApiV1AdministrationAuditLogsGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1AdministrationAuditLogsGet.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
    rb.query('severity', params.severity, {});
    rb.query('entityType', params.entityType, {});
    rb.query('action', params.action, {});
    rb.query('fromUtc', params.fromUtc, {});
    rb.query('toUtc', params.toUtc, {});
    rb.query('searchTerm', params.searchTerm, {});
    rb.query('skip', params.skip, {});
    rb.query('take', params.take, {});
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

apiV1AdministrationAuditLogsGet.PATH = '/api/v1/administration/audit-logs';
