<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ControlEasyReborn.Modules.Visits.Application</RootNamespace>
    <AssemblyName>ControlEasyReborn.Modules.Visits.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ControlEasyReborn.Modules.Visits.Domain\ControlEasyReborn.Modules.Visits.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>