#!/usr/bin/env bash
# shellcheck shell=bash
#
# scripts/worktree-up.sh — bring up a per-feature-branch dev worktree
#
# Usage:
#   scripts/worktree-up.sh [--branch <branch>] [--no-build]
#   scripts/worktree-up.sh --help
#
# This script:
#   1. Detects the current worktree branch (or uses --branch).
#   2. Computes the worktree index, project name, Traefik hostname, and port.
#   3. Generates docker/.env.worktree.<slug> with COMPOSE_PROJECT_NAME,
#      TRAEFIK_HOST, TRAEFIK_PORT, TRAEFIK_HTTPS_PORT, MYSQL_VOLUME_NAME,
#      JWT_SIGNING_KEY.
#   4. Registers the ce-<slug>.localhost hostname via scripts/lib/resolver.sh.
#   5. Generates docker/docker-compose.worktree.<slug>.yml from the template.
#   6. Runs: docker compose -p ce-<slug> -f docker-compose.yml
#           -f docker-compose.worktree.<slug>.yml up -d --build
#   7. Prints the URLs.
#
# Idempotent: re-running on an already-up worktree prints "already up"
# and exits 0.
#
# See .specs/devcontainers/design.md "Worktree bring-up sequence".

set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/worktree.sh
. "$SCRIPT_DIR/lib/worktree.sh"
# shellcheck source=lib/resolver.sh
. "$SCRIPT_DIR/lib/resolver.sh"

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
ce_usage() {
  cat <<'EOF'
Usage: scripts/worktree-up.sh [OPTIONS]

Bring up a per-feature-branch dev worktree with its own Compose project,
Traefik hostname, published port, and MySQL volume.

Options:
  --branch <name>   Use this branch (default: current branch).
  --no-build        Skip `docker compose build` (use existing images).
  --resolver=<m>    Resolver mode: auto (default), nrpt, hosts-file.
  --help, -h        Show this help.

The script must be run from inside a worktree of ControlEasy Reborn
(the worktree directory created by `git worktree add`).
EOF
}

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------
CE_BRANCH=""
CE_NO_BUILD=false
CE_RESOLVER_MODE="auto"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch)
      CE_BRANCH="$2"; shift 2 ;;
    --branch=*)
      CE_BRANCH="${1#--branch=}"; shift ;;
    --no-build)
      CE_NO_BUILD=true; shift ;;
    --resolver=*)
      CE_RESOLVER_MODE="${1#--resolver=}"; shift ;;
    --resolver)
      CE_RESOLVER_MODE="$2"; shift 2 ;;
    --help|-h)
      ce_usage; exit 0 ;;
    *)
      ce_die "Unknown argument: $1 (try --help)" ;;
  esac
done

# ---------------------------------------------------------------------------
# Detect branch + worktree
# ---------------------------------------------------------------------------
if [[ -z "$CE_BRANCH" ]]; then
  CE_BRANCH="$(ce_current_branch)"
fi

# Sanity: refuse to run on the main checkout's default branch unless
# explicitly invoked from there. We detect "main checkout" by the
# absence of the worktree directory pattern in the git worktree list.
SLUG="$(ce_branch_to_slug "$CE_BRANCH")"
PROJECT="$(ce_project_name "$CE_BRANCH")"
HOSTNAME="$(ce_traefik_hostname "$CE_BRANCH")"
PORT="$(ce_allocate_port "$CE_BRANCH")"
HTTPS_PORT=$(( PORT + 1 ))
VOLUME="$(ce_mysql_volume_name "$CE_BRANCH")"
ENV_FILE="$(ce_env_file "$CE_BRANCH")"
OVERRIDE_FILE="$(ce_override_file "$CE_BRANCH")"
TEMPLATE_FILE="$(ce_override_template)"

ce_log "Branch:        $CE_BRANCH"
ce_log "Project:       $PROJECT"
ce_log "Hostname:      $HOSTNAME"
ce_log "Port:          $PORT"
ce_log "HTTPS port:    $HTTPS_PORT"
ce_log "Volume:        $VOLUME"
ce_log "Env file:      $ENV_FILE"
ce_log "Override file: $OVERRIDE_FILE"

# ---------------------------------------------------------------------------
# Idempotency: already up?
# ---------------------------------------------------------------------------
if ce_is_worktree_up "$PROJECT"; then
  ce_log "already up (project=$PROJECT has running containers)"
  exit 0
fi

# ---------------------------------------------------------------------------
# Step 3: Generate .env.worktree.<slug>
# ---------------------------------------------------------------------------
ce_log "Generating $ENV_FILE"
JWT_KEY="$(ce_jwt_signing_key "$CE_BRANCH")"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/worktree-up.sh for branch $CE_BRANCH
# Do not commit — this file is .gitignore'd.
COMPOSE_PROJECT_NAME=$PROJECT
TRAEFIK_HOST=$HOSTNAME
TRAEFIK_PORT=$PORT
TRAEFIK_HTTPS_PORT=$HTTPS_PORT
MYSQL_VOLUME_NAME=$VOLUME
JWT_SIGNING_KEY=$JWT_KEY
EOF
chmod 600 "$ENV_FILE"

# ---------------------------------------------------------------------------
# Step 4: Register hostname via resolver shim
# ---------------------------------------------------------------------------
ce_log "Registering hostname $HOSTNAME -> 127.0.0.1"
resolver_add "$HOSTNAME" "$CE_RESOLVER_MODE"

# ---------------------------------------------------------------------------
# Step 5: Generate docker-compose.worktree.<slug>.yml from template
# ---------------------------------------------------------------------------
if [[ ! -f "$TEMPLATE_FILE" ]]; then
  ce_die "Template not found: $TEMPLATE_FILE (run task 9.3 first)"
fi
ce_log "Generating $OVERRIDE_FILE from $TEMPLATE_FILE"
# The template uses shell-style ${VAR} placeholders; we substitute using env.
# shellcheck disable=SC2002
COMPOSE_PROJECT_NAME="$PROJECT" \
TRAEFIK_HOST="$HOSTNAME" \
TRAEFIK_PORT="$PORT" \
TRAEFIK_HTTPS_PORT="$HTTPS_PORT" \
MYSQL_VOLUME_NAME="$VOLUME" \
JWT_SIGNING_KEY="$JWT_KEY" \
envsubst < "$TEMPLATE_FILE" > "$OVERRIDE_FILE"

# ---------------------------------------------------------------------------
# Step 6: docker compose up -d --build
# ---------------------------------------------------------------------------
export COMPOSE_PROJECT_NAME="$PROJECT"
COMPOSE_FILE_BASE="docker/docker-compose.yml"
if [[ ! -f "$COMPOSE_FILE_BASE" ]]; then
  ce_die "Base compose file not found: $COMPOSE_FILE_BASE"
fi

if [[ "$CE_NO_BUILD" == "true" ]]; then
  ce_log "Skipping build (--no-build)"
  docker compose -p "$PROJECT" \
    --env-file "$ENV_FILE" \
    -f "$COMPOSE_FILE_BASE" \
    -f "$OVERRIDE_FILE" \
    up -d
else
  ce_log "Building and bringing up the stack"
  COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
  docker compose -p "$PROJECT" \
    --env-file "$ENV_FILE" \
    -f "$COMPOSE_FILE_BASE" \
    -f "$OVERRIDE_FILE" \
    up -d --build
fi

# ---------------------------------------------------------------------------
# Step 7: Print URLs
# ---------------------------------------------------------------------------
ce_log "Stack is up."
echo
echo "  Web:      http://$HOSTNAME:$PORT/   (redirects to HTTPS)"
echo "  Web HTTPS: https://$HOSTNAME:$HTTPS_PORT/  (self-signed cert)"
echo "  API:      https://$HOSTNAME:$HTTPS_PORT/api/v1/health"
echo "  Swagger:  https://$HOSTNAME:$HTTPS_PORT/swagger"
echo
echo "  Logs:     docker compose -p $PROJECT logs -f api"
echo "  Tear down: scripts/worktree-down.sh --branch $CE_BRANCH"