/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  displayName?: string | null;
  email?: string | null;
  password?: string | null;
  roles?: string | null;
  tenantId?: string;
}
