/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateEntryLogRequest {
  entryState?: string | null;
  overrideReason?: string | null;
  photoId?: string | null;
  subjectDocument?: string | null;
  subjectName?: string | null;
  subjectType?: string | null;
}
