/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePorteiroRequest {
  displayName?: string | null;
  email?: string | null;
  password?: string | null;
}
