/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateVisitRequest {
  apartmentId?: string | null;
  purpose?: string | null;
  visitorDocument?: string | null;
  visitorName?: string | null;
  visitorPhone?: string | null;
}
