/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateResidentRequest {
  apartmentId?: string | null;
  cpf?: string | null;
  email?: string | null;
  name?: string | null;
  phone?: string | null;
}
