/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAuditLogRequest {
  action?: string | null;
  details?: string | null;
  entityId?: string;
  entityType?: string | null;
  performedByName?: string | null;
  performedByUserId?: string;
}
