/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IssueCredentialRequest {
  expiresAtUtc?: string | null;
  subjectId?: string;
  subjectType?: string | null;
  validFromUtc?: string | null;
}
