/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordAccessScanRequest {
  confirmDuplicate?: boolean;
  direction?: string | null;
  gatehouseId?: string | null;
  qrPayload?: string | null;
  scanAttemptId?: string;
}
