/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordManualAccessRequest {
  direction?: string | null;
  gatehouseId?: string | null;
  lookupAuditId?: string;
  subjectId?: string;
  subjectType?: string | null;
}
