/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCondominiumSettingsRequest {
  allowOverrideOnRefusal?: boolean;
  allowedVisitorEndHour?: string | null;
  allowedVisitorStartHour?: string | null;
  autoCheckoutAtMidnight?: boolean;
  defaultShiftLengthHours?: number;
  emergencyContactPhone?: string | null;
  maxActiveVisitorsPerUnit?: number;
  overdueVisitAlertMinutes?: number;
  photoRequiredProviders?: boolean;
  photoRequiredResidents?: boolean;
  photoRequiredVisitors?: boolean;
  requireShiftHandoverNotes?: boolean;
  visitDurationMinutes?: number;
}
