/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateConsentPolicyRequest {
  dwellTimeLimitMinutes?: number | null;
  photoRequired?: boolean;
  subjectCategory?: string | null;
}
