/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAttendantProfileRequest {
  displayName?: string | null;
  gatehouseId?: string | null;
  permissions?: string | null;
  shiftId?: string | null;
}
