/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateServiceProviderRequest {
  company?: string | null;
  document?: string | null;
  email?: string | null;
  name?: string | null;
  phone?: string | null;
  serviceType?: string | null;
}
