/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VehicleType } from '../models/vehicle-type';
export interface UpdateVehicleRequest {
  apartmentId?: string | null;
  brand?: string | null;
  color?: string | null;
  model?: string | null;
  ownerName?: string | null;
  plate?: string | null;
  vehicleType?: VehicleType;
}
