/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VehicleType } from './vehicle-type';

/**
 * Each possible value of `VehicleType`
 */
export const VEHICLE_TYPE: VehicleType[] = [0, 1, 2, 3];
