using System;

namespace DBTools.Mapping
{
    /// <summary>
    /// Specifies the database table name for a model class.
    /// When not applied, the class name is used as the table name.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    public class TableAttribute : Attribute
    {
        /// <summary>
        /// The database table name.
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// Optional schema name (e.g., "dbo").
        /// </summary>
        public string Schema { get; set; }

        public TableAttribute(string name)
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
        }
    }

    /// <summary>
    /// Specifies the database column name for a property.
    /// When not applied, the property name is used as the column name.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class ColumnAttribute : Attribute
    {
        /// <summary>
        /// The database column name.
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// Optional column type name (e.g., "nvarchar(100)").
        /// </summary>
        public string TypeName { get; set; }

        /// <summary>
        /// Column order for INSERT operations (optional).
        /// </summary>
        public int Order { get; set; } = -1;

        public ColumnAttribute(string name)
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
        }
    }

    /// <summary>
    /// Marks a property as the primary key.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class KeyAttribute : Attribute
    {
        /// <summary>
        /// Whether the key is auto-incremented by the database (default: true).
        /// </summary>
        public bool AutoIncrement { get; set; } = true;
    }

    /// <summary>
    /// Marks a property to be excluded from database operations.
    /// The property will not be included in SELECT, INSERT, or UPDATE queries.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class NotMappedAttribute : Attribute
    {
    }

    /// <summary>
    /// Marks a property as read-only (included in SELECT but excluded from INSERT/UPDATE).
    /// Useful for computed columns.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class DatabaseGeneratedAttribute : Attribute
    {
        public DatabaseGeneratedOption Option { get; }

        public DatabaseGeneratedAttribute(DatabaseGeneratedOption option)
        {
            Option = option;
        }
    }

    /// <summary>
    /// Options for database-generated values.
    /// </summary>
    public enum DatabaseGeneratedOption
    {
        /// <summary>
        /// Value is not generated by the database.
        /// </summary>
        None,

        /// <summary>
        /// Value is generated by the database on insert (identity/auto-increment).
        /// </summary>
        Identity,

        /// <summary>
        /// Value is generated by the database on insert and update (computed column).
        /// </summary>
        Computed
    }

    /// <summary>
    /// Specifies the maximum length of string/binary data.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class MaxLengthAttribute : Attribute
    {
        public int Length { get; }

        public MaxLengthAttribute(int length)
        {
            Length = length;
        }
    }

    /// <summary>
    /// Marks a property as required (NOT NULL in database).
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class RequiredAttribute : Attribute
    {
    }

    /// <summary>
    /// Specifies a foreign key relationship.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class ForeignKeyAttribute : Attribute
    {
        /// <summary>
        /// The name of the navigation property or the foreign key column.
        /// </summary>
        public string Name { get; }

        public ForeignKeyAttribute(string name)
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
        }
    }

    /// <summary>
    /// Marks a property as a concurrency check token (optimistic concurrency).
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class ConcurrencyCheckAttribute : Attribute
    {
    }

    /// <summary>
    /// Marks a property as a timestamp/row version for concurrency control.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class TimestampAttribute : Attribute
    {
    }

    /// <summary>
    /// Specifies a default value for the column.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class DefaultValueAttribute : Attribute
    {
        public object Value { get; }
        public string Sql { get; set; }

        public DefaultValueAttribute(object value)
        {
            Value = value;
        }
    }

    /// <summary>
    /// Specifies a global query filter for the entity (e.g., soft delete).
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
    public class QueryFilterAttribute : Attribute
    {
        /// <summary>
        /// The WHERE clause condition to always apply (e.g., "IsDeleted = 0").
        /// </summary>
        public string Condition { get; }

        public QueryFilterAttribute(string condition)
        {
            Condition = condition ?? throw new ArgumentNullException(nameof(condition));
        }
    }
}
